name: Update latest data
on:
  workflow_dispatch:
  schedule:
    - cron: "30 9,10 * * 5" # Run at 5:30 and 6:30 pm every Thuesday Eastern Time (cron is in UTC)
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: git pull origin master
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/setup-node@v2
        with:
          node-version: "14.16.1"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}-${{ github.ref}}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}-
      - name: Cache gatsby output modules
        uses: actions/cache@v2
        env:
          cache-name: cache-gatsby
        with:
          path: |
            ./.cache
            ./public
          key: ${{ env.cache-name }}-${{ github.ref }}-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.ref }}-
      - name: Install dependencies
        run: yarn install
      - name: Fetch latest data file
        run: ./downloadDataFile.js
      - name: Verify successful build
        run: yarn build
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "Databot"
          message: "Add latest data"